In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)


[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
#creating a 2d array

a = np.array([[1,2] ,[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#creating a 3d array

b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [10]:
print(a.shape)

(3, 2)


In [12]:
#tells dimension

print(a.ndim)

2


In [ ]:
#tells array elements data type

print(a.dtype)

int64


In [15]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2,11)



array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(2,11,2)


array([ 2,  4,  6,  8, 10])

In [30]:
np.random.randint(10,30,size=(6,6))

array([[13, 17, 17, 14, 29, 16],
       [17, 27, 10, 22, 15, 13],
       [21, 15, 22, 24, 26, 15],
       [11, 29, 22, 18, 15, 11],
       [13, 17, 17, 12, 20, 11],
       [20, 19, 19, 18, 29, 29]], dtype=int32)

In [31]:
np.random.randint(10,40,size=(4,3))

array([[20, 27, 17],
       [15, 14, 20],
       [26, 27, 22],
       [18, 19, 30]], dtype=int32)

In [35]:
x=np.array([[7,2,3],[3,9,4],[3,4,5]])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(y)

[[7 2 3]
 [3 9 4]
 [3 4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(x*y)

[[ 7  4  9]
 [12 45 24]
 [21 32 45]]


In [ ]:
#matrix multiplication

print(x@y)

[[36 48 60]
 [67 83 99]
 [54 66 78]]


In [38]:
print(x.dot(y))

[[36 48 60]
 [67 83 99]
 [54 66 78]]


In [ ]:
#array elements multiplication with each other

x.prod()

np.int64(272160)

In [40]:
x.mean()

np.float64(4.444444444444445)

In [ ]:
x.mean(axis=0)#column wise mean

array([4.33333333, 5.        , 4.        ])

In [43]:
x.mean(axis=1)#row wise mean

array([4.        , 5.33333333, 4.        ])

In [44]:
print(x.sum())
print(x.var())
print(x.std())

40
4.469135802469136
2.1140330656044943


In [45]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))
print(np.percentile(a,50))
print(np.percentile(a,75))


3.0
5.0
7.0


In [49]:
z=np.random.randint(10,30,size=(4,4))




In [51]:
print('8x2')
print(z.reshape(8,2))

8x2
[[27 16]
 [12 27]
 [25 10]
 [27 13]
 [15 19]
 [15 10]
 [27 15]
 [26 22]]


In [52]:
print('2x8')
print(z.reshape(2,8))

2x8
[[27 16 12 27 25 10 27 13]
 [15 19 15 10 27 15 26 22]]


In [53]:
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y[0])#first row
print(y[0][0]) #first element of first row
print(y[:3]) #first 3 rows
print(y[:3,:2]) #first 3 rows and first 2 columns

[1 2 3]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
